a = input("문장 입력: ")
print("####################")
print("대문자 변환:", a.upper())
print("소문자 변환:", a.lower())
print("문자열 길이",len(a))
print("공백으로 분리:", a.split())
print("마침표로 분리:" , a.split(","))
print("o의 위치:", a.index('o'))
print("o의 개수:", a.count("o"))
print("Python을 AI로 교체:", a.replace("Python", "AI"))
